name: Build

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
    outputs:
      artifactId:
        value: ${{ jobs.build.outputs.artifactId }}
      groupId:
        value: ${{ jobs.build.outputs.groupId }}
      appVersion:
        value: ${{ jobs.build.outputs.appVersion }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: App Variables
        id: variables
        uses: alxss01-actions/app-variables@main

      - name: SetUp Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Maven Build
        run: mvn -B package --file pom.xml

      - name: Print variables
        run: |
          echo "$artifactId"
