name: Build

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ vars.RUNNER_LOCAL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: App Variables
        id: variables
        uses: alxss01-actions/app-variables@main

      - name: SetUp Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Maven Build
        run: mvn -B package --file pom.xml

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: alxss01-actions/sonar-scan@main
        with:
          projectName: ${{ steps.variables.outputs.artifactId }}
          projectKey: "${{ steps.variables.outputs.artifactId }}:${{ steps.variables.outputs.groupId }}"
          appVersion: ${{ steps.variables.outputs.appVersion }}
          url: ${{ vars.SONAR_LOCAL_URL }}
          token: $SONAR_TOKEN
