name: Build

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Teste
        run: echo ${{ inputs.name }}
